camaraproject/ConnectivityInsights

code/API_definitions/CAMARA Connectivity Insights API.yaml

Initial draft version 0.1.0
Initial API version
Initial draft of API
N/A
```
release-note
```
```
docs
```

Create CAMARA Connectivity Insights API.yaml

---

README.md

* bug
* correction
* cleanup
updated call schedule for this year along with link for the meeting.
* tests
Fixes #
```
release-note
```
```
docs
```

updated call schedule and virtual meeting link.

---

README.md

* bug
* correction
* cleanup
updated the call details
* tests
Fixes #
```
release-note
```
```
docs
```

updated meeting schedule to include timing for the call.

---

code/API_definitions/CAMARA Connectivity Insights API.yaml

Fixes to issues #6 #9 #12 #13  #14
* correction
Fixes issues #6 #9 #12 #13  #14
<!-- Automatically closes linked issue when PR is merged.
Fixes #6 
Fixes #9 
Fixes #12 
Fixes #13
Fixes #14
Added a new type, `policyFullfilmentConfidence`, to encapsulate the `good | bad` estimate  
```
0-2-0-wip Fixes issues #6 #9 #12 #13  #14
```
```
docs
```

0-2-0-WIP multiple issue fixes

---

code/API_definitions/CAMARA Connectivity Insights API.yaml

* bug
* correction
updated yaml to meet the guidelines from identity and consent mgmt working group.
* cleanup
* tests
Fixes #
```
release-note
```
```
docs
```

updates to address issue #28

---

CODEOWNERS
MAINTAINERS.MD

45 update and review codeowners and maintainersmd file

---

code/API_definitions/CAMARA Connectivity Insights API.yaml
code/API_definitions/network-info.yaml

* bug
* correction
* cleanup
* tests
fixes #49 
Fixes #
```
release-note
```
```
docs
```

updated open api version to 3.0.3 as per camara standards

---

.spectral.yml
code/API_definitions/CAMARA Connectivity Insights API.yaml
lint-function/camara-language-avoid-telco.js
lint-function/camara-reserved-words.js
lint-function/camara-security-no-secrets-in-path-or-query-parameters.js

* bug
Re introduced application server object for the API calls.
Also updated spectral and lint-function files to use the latest branch 0.3.0 in commonalities
Fixes #
```
release-note
```
```
docs
```

fix for issue #54

---

README.md

[#### What type of PR is this?
* correction
Fixes Mailing List Subscribe/Unsubscribe link
Fixes Issue #58

Fix Mailing List Subscribe/Unsubscribe link

---

README.md

* correction
Corrected links within README badges
Fixes # na / minor fix

Update README.md - corrected badge links

---

code/API_definitions/application-profiles.yaml
code/API_definitions/connectivity-insights-subscriptions.yaml
code/API_definitions/connectivity-insights.yaml

initial commit for spring25

---

CHANGELOG.md
code/API_definitions/application-profiles.yaml
code/API_definitions/connectivity-insights-subscriptions.yaml
code/API_definitions/connectivity-insights.yaml

Updates of version numbers for alpha.1 pre-release for Spring 25 Meta Release
Fixes #
```
release-note
```
```
docs
```

Updated versions and URL for alpha.1

---

code/API_definitions/application-profiles.yaml

* correction
update version and url to wip / vwip following release
Fixes #124 
```
release-note
```
```
docs
```

update application-profiles version and url to wip / vwip

---

code/API_definitions/connectivity-insights-subscriptions.yaml

* correction
Update connectivity-insights-subscriptions version and url to wip / vwip
Fixes #123 
```
release-note
```
```
docs
```

Update connectivity-insights-subscriptions version and url to wip / vwip

---

code/API_definitions/connectivity-insights.yaml

* correction
Update connectivity-insights.yaml version and url to wip/vwip
Fixes #122 
```
release-note
```
```
docs
```

Update connectivity-insights.yaml version and url to wip/vwip

---

README.md

* correction
Changes call schedule to UTC inline with other CAMARA APIs
Fixes #129 
```
release-note
```
```
docs
```

correction: change schedule from PST to UTC

---

code/API_definitions/connectivity-insights-subscriptions.yaml
code/API_definitions/connectivity-insights.yaml

* correction
Updates `x-camara-commonalities` version to 0.6
Fixes #143 
```
release-note
```
```
docs
```

Update `x-camara-commonalities` to 0.6

---

code/API_definitions/connectivity-insights-subscriptions.yaml

…ons"
* correction
Corrects the `info.title` in the OAS YAML
Fixes #134 
```
release-note
```
```
docs
```

fix : corrected the `info.title` in the OAS YAML

---

code/API_definitions/connectivity-insights-subscriptions.yaml
code/API_definitions/connectivity-insights.yaml

* correction
Removes the 401 Authentication Required error as per Commonalities r3.2
Fixes #138 
```
release-note
```
```
docs
```

fix: removed `401 Authentication Required`

---

code/API_definitions/connectivity-insights-subscriptions.yaml
code/Test_definitions/connectivity-insights-subscriptions.feature

the PR has the changes related to commonalities guidelines for Fall 25 release
Fixes #145 
```
release-note
```
```
docs
```

yaml update for connectivity insights subscription API based on commonalities guidelines for Fall 25
